name: Auto-format with Black + Lint with Pylint

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  format-and-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Black and Pylint
      run: |
        pip install black pylint
        pip install -r requirements.txt

    - name: Auto-format code using Black
      run: |
        black .

    - name: Commit and push formatting changes (if any)
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        if ! git diff-index --quiet HEAD; then
          git commit -m "🤖 Auto-format with Black"
          git push
        fi

    - name: Run Pylint and fail if score < 8
      run: |
        pylint $(git ls-files '*.py') --fail-under=8
